name: AutoExecutor - Unlogged-spring-maven-demo Pipeline

on:
  push:
  pull_request:

jobs:
  AutoExecute:
    runs-on: ubuntu-latest
    steps:

      - name: checkout commit
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle 8.5
        uses: gradle/gradle-build-action@v2
        with:
            gradle-version: 8.5

      - name: clone and run target project
        run: |
            git clone https://github.com/unloggedio/unlogged-spring-maven-demo.git
            docker compose -f unlogged-spring-maven-demo/conf/docker-compose.yml up -d

      - name: Gradle Test
        run: gradle test --tests com.insidious.plugin.auto.AutoExecutorCITest.startUnloggedMavenDemoTest --scan --info

      - name: Store reports
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: reports
          path: |
            **/build/reports/
            **/build/test-results/

      - name: Docker down
        run: docker compose down

